
# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "H8PQ/T2w0OGBgTHMI2xgNWuax0HGSi2/GujKtO+AoiGT2m1rUhZpYayXjDpiXc7tVdpVMgj1Gi20T8geQiBI2eq2e68vT59eUCjYg8pcPTqbLs1j6+8HBLWDadMvz5ztvL+MypEmTDJOl5UCJJlKJ66jGgeCdp7t9At2B1Th2oHPTuPae30JxfZ/GvC1aJiQpKki3jore7PFNEA6IVRfYex85szqZyE21naMcYFKv5/sxZzUcLKvNAk2lhhPPYOF/6SGNrcXQ2z7221iMBwvjCMC6fBootBQ7lVRiIdTLjKXxY9qiqV7YtkUD78ijp18fv7cIv+EyF89ioQaarMQ/ATq/2l3OkXnA+/Vhm2rWe10FR+shTgLkMvZ+98bnfuoDZYj7z4x/J3bZuZo1AcFmiTnZcBFBQFLv4dxzFP7ArWppdf8iL5ysYyTYd6/KYyPG6qL9CfVI39PeA6iQSfa0HptsrCNiY/6EnTh5Sr4o6c1j2wCCZnAjV+FQOAedlqBjEtGwkc/4YkQCQUNo2rg0N0Vpt6ebDaNkARo1VIfErMtfPUfY5aJixM0D8q2xqPIXNYdGvK6HirMTRIT2ONmr0D6YY4pOkpr4fZE7FpSuH/OvC1tTyEENkVCyKAQSxl8c2pPaPV6DGDNFUASOZS52EmQUhY53k/xovghvlGOq2Q="


install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-3.7.3-MacOSX-x86_64.sh"
      wget "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client

      
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
