travis:
  secure:
    BINSTAR_TOKEN: IW9cWSeLBnKCi9rG7FXRpkaE0Cce+zBu8S8yO/EC7VFNb1gIkR7LGJMmJEeIkmsOJbu8ILe9lNmP7NNeMLRTirQWt/tbL9Q8/eBbNuVuerBYFCnB55gx+qJR2X8ehlYiC0cEokMeh96Ry/m1QrMPoA94r/RaWUxq2wZW5NqcmQQ5YFCdrXzxHztBIIMg0h47tLpQO/huuR3aR9DgiAFw08ws9+CarIH2IRiyPmszxxAd4BP8Pg5ACgEjhA5Ar2fL3XyYmOtGdsJLyoRZLLIs0rZP+XISwjwNJq5RCZnLKYgUcLTO63mz9bvFZtzIWn0RZQl1yIm6pqn0kwuICsS63s2J6hIJU0vMqK3WxkPZj6TCxQx1qwhLU2OM02+kkeLIQtq3j4fVdFMS71Bd3dMlRFDkFXonnWoEh+O5SnVFTRfp1/XPKlerGBmhvajVklwrgrzv989pNh5zwTpKCF91jYUyhhxrlq7YhsDfc+kWkF0t2VYWZQo4tl76tV/dnIogxKZy9umi5q3EKLbroZWZI4VyuaJYuwc5Todi1vWaio2tGJI9qLUhWMSyfRiCXDiMj+5m6Fa/u4xaKm9KtD52Af2hn6R44Vq+178g7enyq8evddUAlVpU6nu81DahTgwK9ZCKG5ESaYICFCazry1IzGdkcLd/IrktKtlBo2eBciU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
