travis:
  secure:
    BINSTAR_TOKEN: H8PQ/T2w0OGBgTHMI2xgNWuax0HGSi2/GujKtO+AoiGT2m1rUhZpYayXjDpiXc7tVdpVMgj1Gi20T8geQiBI2eq2e68vT59eUCjYg8pcPTqbLs1j6+8HBLWDadMvz5ztvL+MypEmTDJOl5UCJJlKJ66jGgeCdp7t9At2B1Th2oHPTuPae30JxfZ/GvC1aJiQpKki3jore7PFNEA6IVRfYex85szqZyE21naMcYFKv5/sxZzUcLKvNAk2lhhPPYOF/6SGNrcXQ2z7221iMBwvjCMC6fBootBQ7lVRiIdTLjKXxY9qiqV7YtkUD78ijp18fv7cIv+EyF89ioQaarMQ/ATq/2l3OkXnA+/Vhm2rWe10FR+shTgLkMvZ+98bnfuoDZYj7z4x/J3bZuZo1AcFmiTnZcBFBQFLv4dxzFP7ArWppdf8iL5ysYyTYd6/KYyPG6qL9CfVI39PeA6iQSfa0HptsrCNiY/6EnTh5Sr4o6c1j2wCCZnAjV+FQOAedlqBjEtGwkc/4YkQCQUNo2rg0N0Vpt6ebDaNkARo1VIfErMtfPUfY5aJixM0D8q2xqPIXNYdGvK6HirMTRIT2ONmr0D6YY4pOkpr4fZE7FpSuH/OvC1tTyEENkVCyKAQSxl8c2pPaPV6DGDNFUASOZS52EmQUhY53k/xovghvlGOq2Q=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
