travis:
  secure:
    BINSTAR_TOKEN: V0/GHJsMSdZIj+b+hGV8OeZlUrxi+yevfZOoAps6m3wJpf5GnWU69XGOuE9MUd3a+YBvzlY9Xro0Of9u/mQ/R+VOCJOJuEB1N0F6R7uPq4Bv06q9zCIDZzy2rtv5PCU7Sq1DDpJgBwy3iua3dO6CYGfRXBs+cVen+fWlTuF6R0TcHFlxN94+Ae4Wjc0X4DfJPm8TTr5Vt4VHs6wSQgqaNbTpHCpUI96Dqy5tBnFHzaF/uSnV3Ebhyb5vcW3fJrxOeIU+KjkaOMfeA2J2wbb7VyqvaNa/UAQMG+Wztm9fgxCUKaSzlmQL1tq42ZnDKaA+GdREU98vp0TNiakgdvMe+PLktWVS/fdGSKl35hlOSQr4/V28JU0yoPiNCkQ8SaxPcj2MlA8mJQ3iHZFkMGh2x/V67o77f40VOOGOCsU8lhtqu6hl9MAqb/AYLv+K0LJ9LjsVHo7ZVmxrb5xTx2hUasWnHH2GSb1B9LKSraqCSKLgMD1gxcpu/U2cymcOC8sjqD6no6m5KdPSo4pjldUGuYl5iYr6Zj/EdENU+gaVkTpDnU7tFOC0WGDQHe17jKB+AC3O3Eeo+0n/5qOTJ6Y4Wuf4OLsYPogQBd4K7Ha0Um+EudYy/iiGPE8Et30LX5W+JFs9vakjWDedVoUlYo0OJS0wmRaTMNTGJPgaMcEL7cc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
